package pl.org.mgalezewska.memo.persistence.entity;// default package
// Generated 2015-05-18 20:31:46 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * Memo generated by hbm2java
 */
@Entity
@Table(name = "MEMO", schema = "MEMO")
public class Memo implements java.io.Serializable {

    private Long memoId;
    private String spelling;
    private String reading;
    private String translation;
    private Integer score;
    private String example;
    private Date dateCreated;
    private Date dateUpdated;
    private Set<Board> boards = new HashSet<Board>(0);

    public Memo() {
    }

    public Memo(Long memoId) {
        this.memoId = memoId;
    }

    public Memo(Long memoId, String spelling, String reading, String translation, Integer score, String example,
                Date dateCreated, Date dateUpdated, Set<Board> boards) {
        this.memoId = memoId;
        this.spelling = spelling;
        this.reading = reading;
        this.translation = translation;
        this.score = score;
        this.example = example;
        this.dateCreated = dateCreated;
        this.dateUpdated = dateUpdated;
        this.boards = boards;
    }

    @Id
    @SequenceGenerator(name = "seq", sequenceName = "SEQ_MEMO", allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq")
    @Column(name = "MEMO_ID", unique = true, nullable = false, scale = 0)
    public Long getMemoId() {
        return this.memoId;
    }

    public void setMemoId(Long memoId) {
        this.memoId = memoId;
    }


    @Column(name = "SPELLING", length = 50)
    public String getSpelling() {
        return this.spelling;
    }

    public void setSpelling(String spelling) {
        this.spelling = spelling;
    }


    @Column(name = "READING", length = 50)
    public String getReading() {
        return this.reading;
    }

    public void setReading(String reading) {
        this.reading = reading;
    }


    @Column(name = "TRANSLATION", length = 50)
    public String getTranslation() {
        return this.translation;
    }

    public void setTranslation(String translation) {
        this.translation = translation;
    }


    @Column(name = "SCORE", precision = 8, scale = 0)
    public Integer getScore() {
        return this.score;
    }

    public void setScore(Integer score) {
        this.score = score;
    }


    @Column(name = "EXAMPLE", length = 300)
    public String getExample() {
        return this.example;
    }

    public void setExample(String example) {
        this.example = example;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "DATE_CREATED", length = 7)
    public Date getDateCreated() {
        return this.dateCreated;
    }

    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "DATE_UPDATED", length = 7)
    public Date getDateUpdated() {
        return this.dateUpdated;
    }

    public void setDateUpdated(Date dateUpdated) {
        this.dateUpdated = dateUpdated;
    }

    @ManyToMany(fetch = FetchType.LAZY, mappedBy = "memos")
    public Set<Board> getBoards() {
        return this.boards;
    }

    public void setBoards(Set<Board> boards) {
        this.boards = boards;
    }


}


